import { useEffect, useState, type ReactNode } from "react";
import { getContractor, type ContractorDetail } from "./api";
import { RISK_TIERS, riskTier } from "./risk";

export function ContractorView({ contractorId, onBack, onProject }: { contractorId: string; onBack: () => void; onProject: (projectId: string) => void }) {
  const [contractor, setContractor] = useState<ContractorDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; setContractor(null); setError(null); void getContractor(contractorId).then((result) => active && setContractor(result)).catch((reason: unknown) => active && setError(reason instanceof Error ? reason.message : "Unable to load contractor.")); return () => { active = false; }; }, [contractorId]);
  if (error) return <Frame onBack={onBack}><div role="alert" className="rounded-xl border border-rose-400/30 bg-rose-400/10 p-5 text-rose-100">{error}</div></Frame>;
  if (!contractor) return <Frame onBack={onBack}><div className="rounded-xl border border-slate-800 bg-slate-900/70 p-12 text-center text-sm text-slate-400">Loading contractor portfolio...</div></Frame>;
  const tier = riskTier(contractor.avg_risk_score);
  return <Frame onBack={onBack}><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold tracking-[0.2em] text-cyan-300">CONTRACTOR CLUSTER</p><h2 className="mt-2 font-mono text-2xl font-semibold">{contractor.contractor_id}</h2><p className="mt-2 text-slate-400">Synthetic Tier 2 portfolio - review signals are not findings of wrongdoing.</p></div><span className={`inline-flex w-fit rounded-full px-3 py-1.5 font-semibold ring-1 ring-inset ${RISK_TIERS[tier].badgeClass}`}>Average risk {contractor.avg_risk_score.toFixed(0)} - {RISK_TIERS[tier].label}</span></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><Metric label="Projects awarded" value={contractor.total_projects.toLocaleString()} /><Metric label="Flagged for review" value={contractor.flagged_project_count.toLocaleString()} tone="amber" /><Metric label="Constituencies" value={contractor.constituencies.length.toLocaleString()} /></div></section><div className="mt-6 grid gap-6 lg:grid-cols-[0.7fr_1.3fr]"><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 sm:p-7"><h3 className="text-lg font-semibold">Award footprint</h3><p className="mt-2 text-sm text-slate-400">Constituencies where this synthetic contractor has projects.</p><div className="mt-5 flex flex-wrap gap-2">{contractor.constituencies.map((name) => <span key={name} className="rounded-full bg-cyan-400/10 px-3 py-1.5 text-sm text-cyan-100 ring-1 ring-inset ring-cyan-400/20">{name}</span>)}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 sm:p-7"><h3 className="text-lg font-semibold">Projects in this cluster</h3><p className="mt-2 text-sm text-slate-400">Open a project to inspect its explainable scoring evidence.</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{contractor.projects.map((projectId) => <button type="button" key={projectId} onClick={() => onProject(projectId)} className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-3 text-left font-mono text-sm text-cyan-100 hover:border-cyan-400 hover:bg-slate-800">{projectId}</button>)}</div></section></div></Frame>;
}
function Frame({ children, onBack }: { children: ReactNode; onBack: () => void }) { return <main className="min-h-screen bg-slate-950 text-slate-100"><header className="border-b border-slate-800"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><div><p className="text-xs font-semibold tracking-[0.2em] text-cyan-300">MPLAD TRACE</p><h1 className="mt-1 text-xl font-semibold">Contractor cluster review</h1></div><button type="button" onClick={onBack} className="rounded-md border border-slate-700 px-3 py-2 text-sm font-medium text-slate-200 hover:border-cyan-400 hover:text-cyan-200">Back to project list</button></div></header><div className="mx-auto max-w-7xl px-5 py-8 lg:px-8">{children}</div></main>; }
function Metric({ label, value, tone = "cyan" }: { label: string; value: string; tone?: "cyan" | "amber" }) { return <article className="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><p className="text-sm text-slate-400">{label}</p><p className={`mt-2 text-2xl font-semibold ${tone === "amber" ? "text-amber-200" : "text-cyan-100"}`}>{value}</p></article>; }
