import { useEffect, useState } from "react";
import { getHistory, getPortfolio, getUpload, verifyRecord, verifyRecords, type AuditEntry, type Portfolio, type UploadBatch } from "./api";
import { RISK_TIERS, riskTier } from "./risk";

export function OperationsView({ page, onBack }: { page: "upload" | "analysis" | "history"; onBack: () => void }) {
  const [data, setData] = useState<Portfolio | AuditEntry[] | null>(null);
  const [error, setError] = useState("");
  const [batch, setBatch] = useState<UploadBatch | null>(null);
  useEffect(() => { setError(""); setData(null); if (page === "analysis") void getPortfolio().then(setData).catch((e: Error) => setError(e.message)); if (page === "history") void getHistory().then(setData).catch((e: Error) => setError(e.message)); }, [page]);
  const showBatch = (value: UploadBatch) => { setBatch(value); setError(""); };
  if (page === "upload") return <Frame onBack={onBack} title="Upload projects for review"><p className="text-slate-400">Submit raw project JSON or a CSV header row. Every record is validated, scored through the saved local detector, and retained in your private local upload history.</p><textarea className="mt-4 h-56 w-full rounded border border-slate-700 bg-slate-950 p-3 font-mono text-sm" placeholder='{"project_id":"..."}' id="record" /><div className="mt-3 flex flex-wrap gap-3"><button className="rounded border border-cyan-400 px-3 py-2" onClick={() => { try { void verifyRecord(JSON.parse((document.getElementById("record") as HTMLTextAreaElement).value)).then(showBatch).catch((e: Error) => setError(e.message)); } catch { setError("Enter valid JSON."); } }}>Verify JSON record</button><label className="cursor-pointer rounded border border-slate-700 px-3 py-2">Upload CSV<input className="hidden" type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.currentTarget.files?.[0]; if (!file) return; void file.text().then(parseCsv).then(verifyRecords).then(showBatch).catch((reason: Error) => setError(reason.message)); }} /></label></div>{error && <p className="mt-3 text-rose-200">{error}</p>}{batch && <Results batch={batch} />}</Frame>;
  return <Frame onBack={onBack} title={page === "analysis" ? "Risk analysis" : "My review history"}>{error && <p className="text-rose-200">{error}</p>}{!data && !error && <p className="text-slate-400">Loading…</p>}{page === "analysis" && data && <pre className="overflow-auto rounded bg-slate-950 p-4 text-xs">{JSON.stringify(data, null, 2)}</pre>}{page === "history" && Array.isArray(data) && (data.length ? data.map(entry => <article className="mb-3 rounded border border-slate-700 p-4" key={`${entry.timestamp}-${entry.action}`}><p className="font-medium">{entry.action === "upload" ? "Upload review" : "Portfolio rescan"}</p><p className="mt-1 text-sm text-slate-400">{new Date(entry.timestamp).toLocaleString()} · {entry.input_summary}</p>{entry.upload_id && <button className="mt-3 text-sm text-cyan-200 hover:underline" onClick={() => void getUpload(entry.upload_id!).then(showBatch).catch((e: Error) => setError(e.message))}>Open saved results</button>}</article>) : <p className="text-slate-400">No upload or rescan history yet.</p>)}{batch && <Results batch={batch} />}</Frame>;
}

function parseCsv(text: string): Record<string, unknown>[] { const [header, ...lines] = text.trim().split(/\r?\n/); const fields = header.split(",").map(field => field.trim()); const records = lines.filter(Boolean).map(line => Object.fromEntries(line.split(",").map((value, index) => [fields[index], value.trim()]))); if (!records.length || records.some(record => Object.keys(record).length !== fields.length)) throw new Error("CSV must have a header and complete comma-delimited rows."); return records; }
function Results({ batch }: { batch: UploadBatch }) { return <section className="mt-6 rounded-xl border border-cyan-400/30 bg-cyan-400/5 p-5"><p className="font-semibold">Saved upload #{batch.upload_id} · {batch.record_count} record{batch.record_count === 1 ? "" : "s"}</p><p className="mt-1 text-sm text-slate-400">{batch.message}</p><div className="mt-4 grid gap-3">{batch.results.map((result, index) => <article key={index} className="rounded-lg border border-slate-700 bg-slate-950 p-4"><span className={`rounded-full px-2 py-1 text-xs ${RISK_TIERS[riskTier(result.risk_score)].badgeClass}`}>{result.risk_score} · {result.risk_tier}</span>{result.reasons.map(reason => <p key={`${index}-${reason.text}`} className="mt-3 text-sm"><span className="font-medium text-cyan-200">{reason.code.replace(/_/g, " ")}:</span> {reason.text}</p>)}</article>)}</div></section>; }
function Frame({ title, children, onBack }: { title: string; children: React.ReactNode; onBack: () => void }) { return <main className="min-h-screen bg-slate-950 p-6 text-slate-100"><div className="mx-auto max-w-4xl"><button className="mb-6 rounded border border-slate-700 px-3 py-2" onClick={onBack}>Back to dashboard</button><h1 className="mb-2 text-2xl font-semibold">{title}</h1><p className="mb-5 text-xs text-amber-200">Synthetic Tier 2 demonstration data — review signals only.</p>{children}</div></main>; }
