import { useEffect, useState, type ReactNode } from "react";
import { ArrowLeft } from "lucide-react";
import { getAlerts, getProject, updateAlert, type Alert, type ProjectDetail } from "./api";
import { Badge } from "./components/ui/badge"; import { Button } from "./components/ui/button"; import { Card, CardContent, CardHeader } from "./components/ui/card"; import { Select } from "./components/ui/select"; import { RISK_TIERS, riskTier } from "./risk";
const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const STATUSES: Alert["status"][] = ["new", "under_review", "investigating", "resolved"];
export function ProjectDetailView({ projectId, onBack, onContractor }: { projectId: string; onBack: () => void; onContractor: (id: string) => void }) { const [project, setProject] = useState<ProjectDetail | null>(null); const [alerts, setAlerts] = useState<Alert[]>([]); useEffect(() => { void getProject(projectId).then(setProject); void getAlerts().then(setAlerts); }, [projectId]); if (!project) return <Frame onBack={onBack}><p className="text-sm text-slate-600">Loading project review…</p></Frame>; const tier = riskTier(project.risk_score); const alert = alerts.find(item => item.project_id === project.project_id); const changeStatus = (status: Alert["status"]) => { if (alert) void updateAlert(alert.alert_id, status).then(updated => setAlerts(current => current.map(item => item.alert_id === updated.alert_id ? updated : item))); }; return <Frame onBack={onBack}><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{project.project_id}</h1><p className="mt-1 text-sm text-slate-600">{project.work_category} · {project.mp_constituency}, {project.state}</p></div><div className="flex items-start gap-3"><Badge variant={RISK_TIERS[tier].variant}>{project.risk_score.toFixed(0)} · {RISK_TIERS[tier].label} risk</Badge>{alert && <label className="grid gap-1 text-xs font-medium text-slate-600">Update review status<Select value={alert.status} onChange={event => changeStatus(event.target.value as Alert["status"])}>{STATUSES.map(status => <option key={status} value={status}>{status.replace(/_/g, " ")}</option>)}</Select></label>}</div></div>{alert && <p className="mt-4 text-sm text-slate-600">This updates the same investigation alert shown in the dashboard queue.</p>}<p className="mt-6 border-l-2 border-amber-400 pl-4 text-sm text-slate-700">Synthetic Tier 2 demonstration record. Signals support review; they are not findings of wrongdoing.</p><div className="mt-6 grid gap-6 lg:grid-cols-[2fr_1fr]"><Card><CardHeader><h2 className="font-semibold">Review evidence</h2></CardHeader><CardContent className="space-y-4">{project.reasons.map(reason => <div key={reason.text} className="border-l-2 border-amber-400 pl-4"><p className="text-sm font-medium">{reasonLabel(reason.code)}</p><p className="mt-1 text-sm text-slate-600">{reason.text}</p></div>)}</CardContent></Card><Card><CardHeader><h2 className="font-semibold">Project facts</h2></CardHeader><CardContent className="space-y-4 text-sm"><div><p className="text-slate-500">Contractor</p><button onClick={() => onContractor(project.contractor_id)} className="mt-1 text-blue-700 hover:underline">{project.contractor_id}</button></div><div><p className="text-slate-500">Sanctioned cost</p><p>{currency.format(project.sanctioned_cost_inr)}</p></div><div><p className="text-slate-500">Nearby projects</p><p>{project.nearby_projects.length} within 2 km</p></div></CardContent></Card></div></Frame>; }
function reasonLabel(code: string): string { const labels: Record<string, string> = { detector_agreement: "Confirmed by Multiple Detectors", isolation_detector_signal: "Isolation-Based Detector Signal", neighborhood_detector_signal: "Neighborhood Detector Signal", no_material_warning: "No Material Warning" }; return labels[code] ?? code.replace(/_/g, " ").replace(/\b\w/g, character => character.toUpperCase()); }
function Frame({ children, onBack }: { children: ReactNode; onBack: () => void }) { return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center gap-4 px-4 py-4 sm:px-6"><Button variant="ghost" onClick={onBack}><ArrowLeft className="size-4" />Dashboard</Button><p className="text-lg font-semibold tracking-tight">MPLAD Trace</p></div></header><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6">{children}</div></main>; }
