import { useEffect, useState, type ReactNode } from "react";
import { getProject, type ProjectDetail } from "./api";
import { RISK_TIERS, riskTier } from "./risk";

const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" });

function displayDate(value: string | null): string { return value ? date.format(new Date(`${value}T00:00:00Z`)) : "Not recorded"; }

export function ProjectDetailView({ projectId, onBack, onContractor }: { projectId: string; onBack: () => void; onContractor: (contractorId: string) => void }) {
  const [project, setProject] = useState<ProjectDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; setProject(null); setError(null); void getProject(projectId).then((result) => active && setProject(result)).catch((reason: unknown) => active && setError(reason instanceof Error ? reason.message : "Unable to load the project.")); return () => { active = false; }; }, [projectId]);
  if (error) return <DetailFrame onBack={onBack}><div role="alert" className="rounded-xl border border-rose-400/30 bg-rose-400/10 p-5 text-rose-100">{error}</div></DetailFrame>;
  if (!project) return <DetailFrame onBack={onBack}><div className="rounded-xl border border-slate-800 bg-slate-900/70 p-12 text-center text-sm text-slate-400">Loading project review...</div></DetailFrame>;
  const tier = riskTier(project.risk_score);
  const [longitude, latitude] = project.location.coordinates;
  return <DetailFrame onBack={onBack}>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-mono text-sm text-cyan-300">{project.project_id}</p><h2 className="mt-1 text-2xl font-semibold">{project.work_category}</h2><p className="mt-2 text-slate-400">{project.mp_constituency}, {project.state}</p></div><span className={`inline-flex w-fit rounded-full px-3 py-1.5 font-semibold ring-1 ring-inset ${RISK_TIERS[tier].badgeClass}`}>Risk score {project.risk_score.toFixed(0)} - {RISK_TIERS[tier].label}</span></div><p className="mt-5 border-l-2 border-amber-400 pl-3 text-sm text-amber-100">Synthetic Tier 2 demonstration record. Signals support review; they are not findings of wrongdoing.</p></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_0.7fr]"><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 sm:p-7"><h3 className="text-lg font-semibold">Why this project was flagged</h3><div className="mt-5 grid gap-3">{project.reasons.map((reason) => <article key={`${reason.code}-${reason.text}`} className="rounded-lg border border-amber-400/20 bg-amber-400/5 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-amber-200">{reason.code.replace(/_/g, " ")}</p><p className="mt-2 text-sm leading-6 text-slate-200">{reason.text}</p></article>)}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 sm:p-7"><h3 className="text-lg font-semibold">Review facts</h3><dl className="mt-5 grid gap-4 text-sm"><div><dt className="text-slate-500">Contractor</dt><dd className="mt-1"><button type="button" onClick={() => onContractor(project.contractor_id)} className="font-mono text-xs text-cyan-200 hover:underline">{project.contractor_id}</button></dd></div><Fact label="Sanctioned cost" value={currency.format(project.sanctioned_cost_inr)} /><Fact label="Regional baseline" value={currency.format(project.regional_baseline_cost_inr)} /><Fact label="Units" value={project.units === null ? "Not recorded" : `${project.units} ${project.unit_type ?? ""}`} /><Fact label="Nearby projects (2 km)" value={String(project.nearby_projects.length)} /><Fact label="Coordinates" value={`${latitude.toFixed(4)}, ${longitude.toFixed(4)}`} /></dl></section></div>
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/70 p-5 sm:p-7"><h3 className="text-lg font-semibold">Project timeline</h3><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Timeline label="Recommended" value={project.recommended_date} /><Timeline label="Sanctioned" value={project.sanction_date} /><Timeline label="Started" value={project.start_date} /><Timeline label="Certified complete" value={project.completion_certified_date} /><Timeline label="Funds released" value={project.fund_release_date} /></div></section>
  </DetailFrame>;
}

function DetailFrame({ children, onBack }: { children: ReactNode; onBack: () => void }) { return <main className="min-h-screen bg-slate-950 text-slate-100"><header className="border-b border-slate-800"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><div><p className="text-xs font-semibold tracking-[0.2em] text-cyan-300">MPLAD TRACE</p><h1 className="mt-1 text-xl font-semibold">Project anomaly review</h1></div><button type="button" onClick={onBack} className="rounded-md border border-slate-700 px-3 py-2 text-sm font-medium text-slate-200 hover:border-cyan-400 hover:text-cyan-200">Back to project list</button></div></header><div className="mx-auto max-w-7xl px-5 py-8 lg:px-8">{children}</div></main>; }
function Fact({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div><dt className="text-slate-500">{label}</dt><dd className={`mt-1 text-slate-100 ${mono ? "font-mono text-xs" : ""}`}>{value}</dd></div>; }
function Timeline({ label, value }: { label: string; value: string | null }) { return <div className="border-l border-slate-700 pl-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-200">{displayDate(value)}</p></div>; }
