import { useEffect, useState } from "react";
import { FileUp } from "lucide-react";
import { getAlerts, getHistory, getProject, getProjects, getSummary, getUpload, updateAlert, type Alert, type AuditEntry, type ProjectDetail, type ProjectListItem, type Summary, type UploadBatch } from "./api";
import { SignOutDialog } from "./App";
import { Badge } from "./components/ui/badge";
import { Button } from "./components/ui/button";
import { Card, CardContent, CardHeader } from "./components/ui/card";
import { Select } from "./components/ui/select";
import { Table, TableCell, TableHead } from "./components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./components/ui/tabs";
import { RISK_TIERS, riskTier } from "./risk";

type View = "overview" | "projects" | "analysis" | "alerts" | "history";
const STATUS_OPTIONS: Alert["status"][] = ["new", "under_review", "investigating", "resolved"];
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0, notation: "compact" });

export function RiskEngine({ onUpload, onContractor, onSignOut }: { onUpload: () => void; onContractor: (id: string) => void; onSignOut: () => void }) {
  const [view, setView] = useState<View>("overview");
  const [summary, setSummary] = useState<Summary | null>(null);
  const [projects, setProjects] = useState<ProjectListItem[]>([]);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [history, setHistory] = useState<AuditEntry[]>([]);
  const [savedUpload, setSavedUpload] = useState<(UploadBatch & { created_at: string }) | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const refreshAlerts = () => void getAlerts().then(setAlerts);
  useEffect(() => { void getSummary().then(setSummary); refreshAlerts(); void getHistory().then(setHistory); void getProjects({ page: 1, pageSize: 25, state: "", workCategory: "", minRisk: "", sortBy: "risk_score", order: "desc" }).then(value => setProjects(value.results)); }, []);
  const openProject = (projectId: string) => { setSelected(projectId); setView("analysis"); };
  const changeStatus = (alertId: number, status: Alert["status"]) => void updateAlert(alertId, status).then(updated => setAlerts(current => current.map(alert => alert.alert_id === updated.alert_id ? updated : alert)));
  return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><div><p className="text-lg font-semibold tracking-tight">MPLAD Trace</p><p className="text-sm text-slate-500">Synthetic Tier 2 project review</p></div><div className="flex gap-2"><Button variant="outline" onClick={onUpload}><FileUp className="size-4" />Upload file</Button><SignOutDialog onSignOut={onSignOut} /></div></div></header><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><Tabs value={view} onValueChange={value => setView(value as View)}><div className="flex flex-col gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-center sm:justify-between"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="projects">Projects</TabsTrigger><TabsTrigger value="analysis">Risk analysis</TabsTrigger><TabsTrigger value="alerts">Alerts ({alerts.filter(alert => alert.status === "new").length})</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList><p className="text-sm text-slate-500">System online · Local synthetic demo</p></div><TabsContent value="overview" className="mt-6"><Overview summary={summary} projects={projects.slice(0, 5)} onOpen={openProject} /></TabsContent><TabsContent value="projects" className="mt-6"><ProjectTable projects={projects} onOpen={openProject} title="Projects" /></TabsContent><TabsContent value="analysis" className="mt-6"><Analysis id={selected} alerts={alerts} onContractor={onContractor} onStatusChange={changeStatus} /></TabsContent><TabsContent value="alerts" className="mt-6"><AlertsTable alerts={alerts} onOpen={openProject} onStatusChange={changeStatus} /></TabsContent><TabsContent value="history" className="mt-6"><History entries={history} savedUpload={savedUpload} onOpenUpload={id => void getUpload(id).then(setSavedUpload)} /></TabsContent></Tabs></div></main>;
}

function Overview({ summary, projects, onOpen }: { summary: Summary | null; projects: ProjectListItem[]; onOpen: (id: string) => void }) { return <div><h1 className="text-2xl font-semibold tracking-tight">Portfolio overview</h1><p className="mt-1 text-sm text-slate-600">Explainable review signals for calibrated synthetic project records.</p><dl className="mt-6 grid divide-y divide-slate-200 border-y border-slate-200 sm:grid-cols-3 sm:divide-x sm:divide-y-0">{[["Projects", summary?.total_projects], ["Flagged for review", summary?.total_flagged], ["Average score", summary?.avg_risk_score?.toFixed(1)]].map(([label, value]) => <div key={String(label)} className="py-4 sm:px-5"><dt className="text-sm text-slate-500">{label}</dt><dd className="mt-1 text-2xl font-semibold tabular-nums">{value?.toLocaleString?.() ?? "—"}</dd></div>)}</dl><div className="mt-8"><ProjectTable projects={projects} onOpen={onOpen} title="Priority review queue" /></div></div>; }
function ProjectTable({ projects, onOpen, title }: { projects: ProjectListItem[]; onOpen: (id: string) => void; title: string }) { return <Card><CardHeader><h2 className="font-semibold">{title}</h2></CardHeader><Table><thead className="border-b border-slate-200 bg-slate-50"><tr><TableHead>Project</TableHead><TableHead>Contractor</TableHead><TableHead>Cost</TableHead><TableHead>Risk</TableHead><TableHead /></tr></thead><tbody>{projects.map(project => { const tier = riskTier(project.risk_score); return <tr key={project.project_id} className="border-b border-slate-100 hover:bg-slate-50"><TableCell className="font-mono text-xs">{project.project_id}</TableCell><TableCell>{project.contractor_id}</TableCell><TableCell>{money.format(project.sanctioned_cost_inr)}</TableCell><TableCell><Badge variant={RISK_TIERS[tier].variant}>{project.risk_score.toFixed(0)} · {RISK_TIERS[tier].label}</Badge></TableCell><TableCell><Button variant="ghost" size="sm" onClick={() => onOpen(project.project_id)}>Review</Button></TableCell></tr>; })}</tbody></Table></Card>; }
function AlertsTable({ alerts, onOpen, onStatusChange }: { alerts: Alert[]; onOpen: (id: string) => void; onStatusChange: (id: number, status: Alert["status"]) => void }) { return <Card><CardHeader><h1 className="font-semibold">Investigation alerts</h1></CardHeader><Table><thead className="border-b border-slate-200 bg-slate-50"><tr><TableHead>Project</TableHead><TableHead>Signal</TableHead><TableHead>Risk</TableHead><TableHead>Status</TableHead><TableHead /></tr></thead><tbody>{alerts.map(alert => <tr key={alert.alert_id} className="border-b border-slate-100 hover:bg-slate-50"><TableCell className="font-mono text-xs">{alert.project_id}</TableCell><TableCell className="capitalize">{alert.anomaly_type.replace(/_/g, " ")}</TableCell><TableCell><Badge variant={RISK_TIERS[riskTier(alert.risk_score)].variant}>{alert.risk_score.toFixed(0)}</Badge></TableCell><TableCell><Select aria-label={`Status for ${alert.project_id}`} value={alert.status} onChange={event => onStatusChange(alert.alert_id, event.target.value as Alert["status"])}>{STATUS_OPTIONS.map(status => <option key={status} value={status}>{status.replace(/_/g, " ")}</option>)}</Select></TableCell><TableCell><Button variant="ghost" size="sm" onClick={() => onOpen(alert.project_id)}>Review</Button></TableCell></tr>)}</tbody></Table></Card>; }
function Analysis({ id, alerts, onContractor, onStatusChange }: { id: string | null; alerts: Alert[]; onContractor: (id: string) => void; onStatusChange: (id: number, status: Alert["status"]) => void }) { const [project, setProject] = useState<ProjectDetail | null>(null); useEffect(() => { if (id) void getProject(id).then(setProject); }, [id]); if (!project) return <div className="border border-dashed border-slate-300 p-8 text-sm text-slate-600">Select a project from Overview, Projects, or Alerts to inspect its evidence.</div>; const tier = riskTier(project.risk_score); const alert = alerts.find(item => item.project_id === project.project_id); return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{project.project_id}</h1><p className="mt-1 text-sm text-slate-600">{project.work_category} · {project.mp_constituency}</p></div><div className="flex items-start gap-3"><Badge variant={RISK_TIERS[tier].variant}>{project.risk_score.toFixed(0)} · {RISK_TIERS[tier].label} risk</Badge>{alert && <label className="grid gap-1 text-xs font-medium text-slate-600">Update review status<Select value={alert.status} onChange={event => onStatusChange(alert.alert_id, event.target.value as Alert["status"])}>{STATUS_OPTIONS.map(status => <option key={status} value={status}>{status.replace(/_/g, " ")}</option>)}</Select></label>}</div></div>{alert ? <p className="text-sm text-slate-600">Set the outcome here; it updates this same alert in the investigation queue.</p> : <p className="text-sm text-slate-600">This project is below the alert threshold and has no persisted investigation record.</p>}<div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><Card><CardHeader><h2 className="font-semibold">Review evidence</h2></CardHeader><CardContent className="space-y-4">{project.reasons.map(reason => <div key={reason.text} className="border-l-2 border-amber-400 pl-4"><p className="text-sm font-medium">{reasonLabel(reason.code)}</p><p className="mt-1 text-sm text-slate-600">{reason.text}</p></div>)}</CardContent></Card><Card><CardHeader><h2 className="font-semibold">Project facts</h2></CardHeader><CardContent className="space-y-4 text-sm"><div><p className="text-slate-500">Contractor</p><button className="mt-1 text-blue-700 hover:underline" onClick={() => onContractor(project.contractor_id)}>{project.contractor_id}</button></div><div><p className="text-slate-500">Sanctioned cost</p><p>{money.format(project.sanctioned_cost_inr)}</p></div><div><p className="text-slate-500">Nearby projects</p><p>{project.nearby_projects.length} within 2 km</p></div></CardContent></Card></div></div>; }
function reasonLabel(code: string): string { const labels: Record<string, string> = { detector_agreement: "Confirmed by Multiple Detectors", isolation_detector_signal: "Isolation-Based Detector Signal", neighborhood_detector_signal: "Neighborhood Detector Signal", no_material_warning: "No Material Warning" }; return labels[code] ?? code.replace(/_/g, " ").replace(/\b\w/g, character => character.toUpperCase()); }
function History({ entries, savedUpload, onOpenUpload }: { entries: AuditEntry[]; savedUpload: (UploadBatch & { created_at: string }) | null; onOpenUpload: (id: number) => void }) { return <Card><CardHeader><h1 className="font-semibold">Review history</h1></CardHeader><CardContent className="space-y-4">{entries.length ? entries.map(entry => <div key={`${entry.timestamp}-${entry.action}`} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3 text-sm"><div><p className="font-medium">{entry.action.replace(/_/g, " ")}</p><p className="text-slate-500">{entry.input_summary}</p></div>{entry.upload_id && <Button variant="outline" size="sm" onClick={() => onOpenUpload(entry.upload_id!)}>Open saved result</Button>}</div>) : <p className="text-sm text-slate-600">No saved review actions yet.</p>}{savedUpload && <div className="border-t border-slate-200 pt-4"><p className="font-medium">Saved upload #{savedUpload.upload_id}</p>{savedUpload.results.map((result, index) => <div key={index} className="mt-2 text-sm text-slate-600"><p>{result.risk_score} · {result.risk_tier}</p>{result.reasons.map(reason => <p key={reason.text} className="mt-1">{reason.text}</p>)}</div>)}</div>}</CardContent></Card>; }
