import { useEffect, useState } from "react";
import { getAlerts, getPortfolio, getProject, getProjects, getSummary, simulate, updateAlert, type Alert, type Portfolio, type ProjectDetail, type ProjectListItem, type Simulation, type Summary } from "./api";
import { RISK_TIERS, riskTier } from "./risk";

type View = "overview" | "projects" | "analysis" | "logic" | "alerts";
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0, notation: "compact" });

export function RiskEngine({ onContractor }: { onContractor: (contractorId: string) => void }) {
  const [view, setView] = useState<View>("overview");
  const [summary, setSummary] = useState<Summary | null>(null);
  const [portfolio, setPortfolio] = useState<Portfolio | null>(null);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [projects, setProjects] = useState<ProjectListItem[]>([]);
  const [selected, setSelected] = useState<string | null>(null);
  const refresh = () => { void getSummary().then(setSummary); void getPortfolio().then(setPortfolio); void getAlerts().then(setAlerts); };
  useEffect(refresh, []);
  useEffect(() => { if (view === "projects" || view === "overview") void getProjects({ page: 1, pageSize: view === "overview" ? 5 : 25, state: "", workCategory: "", minRisk: "", sortBy: "risk_score", order: "desc" }).then(value => setProjects(value.results)); }, [view]);
  const open = (id: string) => { setSelected(id); setView("analysis"); };
  return <div className="min-h-screen bg-[#07111f] text-slate-100"><aside className="fixed inset-y-0 hidden w-64 border-r border-slate-800 bg-[#081827] p-6 lg:block"><p className="text-lg font-bold tracking-wider text-cyan-200">MPLAD TRACE</p><p className="mt-1 text-[10px] tracking-[.22em] text-slate-500">RISK INTELLIGENCE ENGINE</p><nav className="mt-10 grid gap-2">{([['overview','Overview'],['projects','Projects'],['analysis','Risk Analysis'],['logic','Detection Logic'],['alerts','Alerts']] as const).map(([key,label]) => <button key={key} onClick={() => setView(key)} className={`rounded-lg px-3 py-3 text-left text-sm ${view === key ? "bg-cyan-400/15 text-cyan-100" : "text-slate-400 hover:bg-slate-800"}`}>{label}{key === "alerts" ? ` (${alerts.filter(a => a.status === "new").length})` : ""}</button>)}</nav><p className="absolute bottom-6 text-xs text-emerald-300">System online · Local synthetic demo</p></aside><main className="lg:ml-64"><header className="border-b border-slate-800 bg-[#0a1625] px-6 py-5"><p className="text-xs font-semibold tracking-[.2em] text-cyan-300">RISK INTELLIGENCE ENGINE</p><h1 className="mt-1 text-2xl font-semibold">{({ overview: "Command Overview", projects: "Project Intelligence Register", analysis: "Project Risk Analysis", logic: "Detection Logic", alerts: "Sentinel Investigation Alerts" } as Record<View,string>)[view]}</h1></header><div className="p-6">{view === "overview" && <Overview summary={summary} portfolio={portfolio} projects={projects} onOpen={open} />}{view === "projects" && <ProjectTable projects={projects} onOpen={open} title="Prioritized review queue" />}{view === "analysis" && <Analysis id={selected} onContractor={onContractor} />}{view === "logic" && <Logic />}{view === "alerts" && <Alerts alerts={alerts} onOpen={open} onUpdate={(id, status) => void updateAlert(id, status).then(refresh)} />}</div></main></div>;
}

function Overview({ summary, portfolio, projects, onOpen }: { summary: Summary | null; portfolio: Portfolio | null; projects: ProjectListItem[]; onOpen: (id: string) => void }) { return <div className="grid gap-5"><section className="grid gap-4 md:grid-cols-4">{[["Total projects", summary?.total_projects], ["High risk", portfolio?.tiers.red], ["Medium risk", portfolio?.tiers.amber], ["Low risk", portfolio?.tiers.green]].map(([label, value]) => <article key={String(label)} className="rounded-xl border border-slate-800 bg-[#0c1b2b] p-5"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-3 text-3xl text-cyan-100">{value?.toLocaleString?.() ?? "—"}</p></article>)}</section><ProjectTable projects={projects} onOpen={onOpen} title="Top high-risk projects" /></div>; }
function ProjectTable({ projects, onOpen, title }: { projects: ProjectListItem[]; onOpen: (id: string) => void; title: string }) { return <section className="rounded-xl border border-slate-800 bg-[#0c1b2b] p-5"><h2 className="font-semibold">{title}</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th>Project</th><th>Contractor</th><th>Cost</th><th>Risk</th><th /></tr></thead><tbody>{projects.map(project => <tr key={project.project_id} className="border-t border-slate-800"><td className="py-4 font-mono text-cyan-100">{project.project_id}</td><td>{project.contractor_id}</td><td>{money.format(project.sanctioned_cost_inr)}</td><td><span className={`rounded-full px-2 py-1 ${RISK_TIERS[riskTier(project.risk_score)].badgeClass}`}>{project.risk_score.toFixed(0)}</span></td><td><button type="button" onClick={() => onOpen(project.project_id)} className="text-cyan-200 hover:underline">Analyze</button></td></tr>)}</tbody></table></div></section>; }
function Analysis({ id, onContractor }: { id: string | null; onContractor: (contractorId: string) => void }) { const [project, setProject] = useState<ProjectDetail | null>(null); useEffect(() => { if (id) void getProject(id).then(setProject); }, [id]); if (!project) return <p className="text-slate-400">Select a project to begin analysis.</p>; const tier = riskTier(project.risk_score); return <div className="grid gap-5"><section className="rounded-xl border border-slate-800 bg-[#0c1b2b] p-6"><p className="font-mono text-cyan-200">{project.project_id}</p><h2 className="mt-1 text-xl font-semibold">{project.work_category}</h2><p className="mt-2 text-slate-400">{project.mp_constituency} · <button type="button" onClick={() => onContractor(project.contractor_id)} className="text-cyan-200 hover:underline">{project.contractor_id}</button></p><p className={`mt-4 inline-flex rounded-full px-3 py-1 ${RISK_TIERS[tier].badgeClass}`}>Risk {project.risk_score.toFixed(0)} · {tier}</p></section><section className="rounded-xl border border-slate-800 bg-[#0c1b2b] p-5"><h3 className="font-semibold">Why this project requires review</h3>{project.reasons.map(reason => <article key={reason.text} className="mt-3 rounded-lg border border-amber-400/20 p-4"><p className="text-xs uppercase text-amber-200">{reason.code.replace(/_/g, " ")}</p><p className="mt-2 text-sm">{reason.text}</p></article>)}</section></div>; }
function Logic() { const [cost, setCost] = useState(1.2); const [result, setResult] = useState<Simulation | null>(null); useEffect(() => { void simulate({ cost_ratio: cost }).then(setResult); }, [cost]); return <section className="rounded-xl border border-slate-800 bg-[#0c1b2b] p-6"><h2 className="font-semibold">Live interactive anomaly simulator</h2><label className="mt-4 grid gap-2">Cost-to-baseline ratio: {cost.toFixed(1)}x<input type="range" min="0.5" max="4" step="0.1" value={cost} onChange={event => setCost(Number(event.target.value))} /></label><p className="mt-4 text-3xl text-cyan-100">{result?.risk_score.toFixed(0) ?? "…"}</p>{result?.reasons.map(reason => <p className="mt-2 text-sm" key={reason.text}>{reason.text}</p>)}</section>; }
function Alerts({ alerts, onOpen, onUpdate }: { alerts: Alert[]; onOpen: (id: string) => void; onUpdate: (id: number, status: Alert["status"]) => void }) { return <section className="grid gap-3">{alerts.map(alert => <article key={alert.alert_id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-800 bg-[#0c1b2b] p-4"><span className="font-mono text-cyan-100">{alert.project_id}</span><span>{alert.risk_score.toFixed(0)} · {alert.status}</span><select value={alert.status} onChange={event => onUpdate(alert.alert_id, event.target.value as Alert["status"])} className="rounded border border-slate-700 bg-slate-950 p-2"><option value="new">New</option><option value="under_review">Under review</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option></select><button type="button" className="text-cyan-200 hover:underline" onClick={() => onOpen(alert.project_id)}>Investigate</button></article>)}</section>; }
