import { useState } from "react";
import { extractFile, scoreExtraction, type Extraction, type StoryBatch } from "./api";

export function UploadStory() {
  const [extraction, setExtraction] = useState<Extraction | null>(null);
  const [record, setRecord] = useState<Record<string, string>>({});
  const [result, setResult] = useState<StoryBatch | null>(null);
  const [error, setError] = useState("");
  return <main className="min-h-screen bg-[#07111f] p-6 text-slate-100"><div className="mx-auto max-w-5xl"><p className="text-xs tracking-[.2em] text-cyan-300">MPLAD TRACE · LOCAL REVIEW</p><h1 className="mt-2 text-3xl font-semibold">Upload file</h1><p className="mt-2 text-slate-400">Extract fields first, correct anything uncertain, then score with the existing local detector.</p><section className="mt-6 rounded-xl border border-slate-800 bg-[#0c1b2b] p-5"><label className="cursor-pointer rounded border border-cyan-400 px-4 py-2 text-cyan-100">Choose file<input className="hidden" type="file" accept=".csv,.xlsx,.xls,.docx,.pdf,.png,.jpg,.jpeg" onChange={event => { const file = event.target.files?.[0]; if (file) void extractFile(file).then(value => { setExtraction(value); setRecord(value.record); setResult(null); }).catch((reason: Error) => setError(reason.message)); }} /></label>{error && <p className="mt-3 text-rose-200">{error}</p>}</section>{extraction && <section className="mt-5 rounded-xl border border-slate-800 bg-[#0c1b2b] p-5"><h2>Confirm extracted fields</h2>{Object.entries(record).map(([key, value]) => <label className="mt-3 grid gap-1" key={key}>{key}<input className="rounded bg-slate-950 p-2" value={value} onChange={event => setRecord({ ...record, [key]: event.target.value })} /></label>)}<button className="mt-5 rounded border border-cyan-400 px-4 py-2" onClick={() => void scoreExtraction(record, extraction).then(setResult).catch((reason: Error) => setError(reason.message))}>Confirm & score</button></section>}{result && <section className="mt-5 rounded-xl border border-cyan-400/30 p-5"><h2>Finding story</h2><p className="mt-3">{result.results[0].story.deterministic}</p></section>}</div></main>;
}
